#Feature Extraction with Univariate Statistical Test (Chi-Square)

In [1]:

from pandas import read_csv
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [2]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [3]:
#Load Data
filename=('/content/drive/MyDrive/pima-indians-diabetes.data.csv')
names=['preg','plas','pres','skin','test','mass','pedi','age','class']
df=read_csv(filename,names=names)
df.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [4]:
array=df.values
X=array[:,:8]
Y=array[:,8]

In [5]:
#Feature Extraction
test=SelectKBest(score_func=chi2,k=4)
fit=test.fit(X,Y)

In [7]:
#summarize score
set_printoptions(precision=3)
print(fit.scores_)

[ 111.52  1411.887   17.605   53.108 2175.565  127.669    5.393  181.304]


In [8]:
df.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

#Recursive Feature Elimination

In [9]:
#Feature Extraction with RFE
from pandas import read_csv
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression


In [11]:
#load Data
filename=('/content/drive/MyDrive/pima-indians-diabetes.data.csv')
names=['preg','plas','pres','skin','test','mass','pedi','age','class']
RFE_df=read_csv(filename,names=names)
RFE_df.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [14]:
array=RFE_df.values
X=array[:,0:8]
Y=array[:,8]


In [15]:
#Feature Extraction
model=LogisticRegression(max_iter=400)
rfe=RFE(model,n_features_to_select=3)
fit=rfe.fit(X,Y)

In [16]:
#Num Features
fit.n_features_

3

In [17]:
#selected feature
fit.support_

array([ True, False, False, False, False,  True,  True, False])

In [18]:
#feature ranking
fit.ranking_

array([1, 2, 4, 6, 5, 1, 1, 3])

In [19]:
RFE_df.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

#Feature importance using Decision Tree

In [20]:
#Feature importance with Tree Classifier
from pandas import read_csv
from sklearn.tree import DecisionTreeClassifier


In [21]:
#load Data
filename=('/content/drive/MyDrive/pima-indians-diabetes.data.csv')
names=['preg','plas','pres','skin','test','mass','pedi','age','class']
tc_df=read_csv(filename,names=names)

In [27]:
array=tc_df.values
X=array[:,0:8]
Y=array[:,8]

In [28]:
#feature extraction
model=DecisionTreeClassifier()
model.fit(X,Y)

DecisionTreeClassifier()

In [29]:
model.feature_importances_

array([0.057, 0.314, 0.084, 0.027, 0.042, 0.223, 0.122, 0.132])

In [30]:
tc_df.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1